<?php

namespace SejourBundle\Repository;

/**
 * AnimCongesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimCongesRepository extends \Doctrine\ORM\EntityRepository
{
}
