<?php

namespace SejourBundle\Repository;

/**
 * CateActiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CateActiRepository extends \Doctrine\ORM\EntityRepository
{
}
