<?php

namespace SejourBundle\Repository;

/**
 * EvenementLiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementLiesRepository extends \Doctrine\ORM\EntityRepository
{
}
