<?php

namespace SejourBundle\Repository;

/**
 * ForumUserMessageVuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumUserMessageVuRepository extends \Doctrine\ORM\EntityRepository
{
}
