<?php

namespace SejourBundle\Repository;

/**
 * ForumCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
