<?php

namespace SejourBundle\Repository;

/**
 * ForumMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
