<?php

namespace SejourBundle\Repository;

/**
 * idMomentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class idMomentRepository extends \Doctrine\ORM\EntityRepository
{
}
