<?php

namespace SejourBundle\Repository;

/**
 * MomentActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MomentActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
