<?php

namespace SejourBundle\Repository;

/**
 * ProblemesEnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemesEnfantRepository extends \Doctrine\ORM\EntityRepository
{
}
