<?php

namespace SejourBundle\Repository;

/**
 * TraitementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraitementJourRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	* Récupération des traitement/jour/séjour.
	*/
	function traitementsejour($id, $jour)
    {
        $query = 	$this->createQueryBuilder('p')
						->addSelect('t')
						->addSelect('e')
						->join('p.Traitement', 't')
						->join('t.enfant', 'e')
						->join('e.sejour', 's')
						->andWhere('s.id = :id')
						->andWhere('p.jour = :jour')
						->addOrderBy('e.prenom', 'ASC')
						->addOrderBy('p.jour', 'ASC')
						->setParameters(array(
							'id'  => $id, 'jour' => $jour));

        return $query->getQuery()->getArrayResult();
    }
	
}
