<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function animRecrute($id)
	{
		$qb = $this->createQueryBuilder('j')
		->select('j.id', 'j.nom', 'j.prenom');

		$sub = $this->createQueryBuilder('t');
		$sub->select("u.id");
		$sub->from("SejourBundle\Entity\AnimSejour","u");
		$sub->andWhere('u.user = j.id');
		$sub->andWhere('u.sejour = :sejour_id');
		$qb->andWhere($qb->expr()->not($qb->expr()->exists($sub->getDQL())));
		$qb->setParameter('sejour_id', $id)->orderBy('j.prenom', 'ASC');
		$results = $qb->getQuery()->getResult(); // 
		return $results;
	}
	
}
