sejour_homepage:
    path:     /home
    defaults: { _controller: SejourBundle:Sejour:index }
sejour_indexsejour:
    path:   /indexsejour
    defaults: { _controller: SejourBundle:Sejour:indexSejour }
table_acti_util:
    path:   /json/activite/datatable
    defaults: { _controller: SejourBundle:Activite:tableActiUtil }
activite_util:
    path:   /activite
    defaults: { _controller: SejourBundle:Activite:activiteUtil }
util_activite_edit:
    path:   /activite/{idActi}/edit
    defaults: { _controller: SejourBundle:Anim:editActiviteUtil }
sejour_creer:
    path:   /creer
    defaults: { _controller: SejourBundle:Sejour:creerSejour }
sejour_edit:
    path:   /{id}
    defaults: { _controller: SejourBundle:Sejour:accueilSejour }
sejour_liste_enfants:
    path:   /{id}/enfants
    defaults: { _controller: SejourBundle:Enfant:listeEnfantSejour }
sejour_equipe:
    path:   /{id}/equipe
    defaults: { _controller: SejourBundle:Anim:listeAnimSejour }
sejour_forum:
    path:   /{id}/forum
    defaults: { _controller: SejourBundle:Forum:accueilForum }
abonnement_forum:
    path:   /{id}/forum/{forum}/gestionAbo
    defaults: { _controller: SejourBundle:Forum:forumAbonnement }
sejour_discussion:
    path:   /{id}/forum{idForum}/{page}
    defaults: { _controller: SejourBundle:Forum:discussion, page: 1}
sejour_activite:
    path:   /{id}/activite
    defaults: { _controller: SejourBundle:Activite:fichesActiSejour }
sejour_planning_conges:
    path:   /{id}/conges
    defaults: { _controller: SejourBundle:Anim:planningConges }
sejour_soins:
    path:   /{id}/soins/{jour}
    defaults: { _controller: SejourBundle:Soin:registreSoins, jour:null }
sejour_traitement:
    path:   /{id}/traitement/{jour}
    defaults: { _controller: SejourBundle:Soin:traitement, jour:null }
sejour_traitement_check:
    path:   /{id}/traitement/check/{jour}/{traitement}/{moment}
    defaults: { _controller: SejourBundle:Soin:checkTraitement }    
sejour_soins_cloture:
    path:   /{id}/soins/{jour}/cloture
    defaults: { _controller: SejourBundle:Soin:clotureSoins}
sejour_activite_edit:
    path:   /{id}/activite/{idActi}/edit
    defaults: { _controller: SejourBundle:Sejour:editActiviteSejour }
sejour_add_activite:
    path:   /{id}/activite/add
    defaults: { _controller: SejourBundle:Activite:ajouterFichesActiSejour }
sejour_suppr_activite:
    path:   /{id}/suppr/{idActi}
    defaults: { _controller: SejourBundle:Activite:supprFichesActiSejour }
table_acti_sejour:
    path:   /json/{id}/activite/datatable
    defaults: { _controller: SejourBundle:Activite:tableActi }
derecrute:
    path:   /derecrute/{id}
    defaults: { _controller: SejourBundle:Anim:derecrute }
table_enfants:
    path:   /json/{id}/datatable
    defaults: { _controller: SejourBundle:Enfant:tableEnfants }
listing_toPdf:
    path:   /{idSej}/trombi/simple
    defaults:  { _controller: SejourBundle:Listing:listingToPdf }
listingComplet_toPdf:
    path:   /{idSej}/trombi/complet
    defaults:  { _controller: SejourBundle:Listing:listingCompletToPdf }
listingRegimes_toPdf:
    path:   /{idSej}/trombi/regimes
    defaults:  { _controller: SejourBundle:Listing:listingRegimeToPdf }
sejour_supprimer:
    path:   /supprimer/{id}
    defaults: { _controller: SejourBundle:Sejour:supprimerSejour }
enfant_edit:
    path:   /enfant/edit/{id}
    defaults: { _controller: SejourBundle:Enfant:editEnfant }
enfant_probleme_list:
    path:   /sejour/enfant/{id}
    defaults: { _controller: SejourBundle:Enfant:problemeEnfant }
enfant_check_probleme:
    path:   /enfant/{id}/check
    defaults: { _controller: SejourBundle:Enfant:problemeEnfantCheck }
enfant_supprimer:
    path:   /enfant/supprimer/{id}
    defaults: { _controller: SejourBundle:Enfant:supprimerEnfant }
enfant_planning_enfant:
    path:   /enfant/{id}/planning
    defaults: { _controller: SejourBundle:Enfant:planningEnfant }
activite_indexactivite:
    path: /activite/
    defaults: { _controller: SejourBundle:Activite:activite }
activite_creer:
    path:   /activite/creer
    defaults: { _controller: SejourBundle:Activite:creerActivite }
jour_indexjour:
    path:   /jour/{id}
    defaults: { _controller: SejourBundle:Jour:jour }
jour_addevent:
    path:   /jour/{id}/add
    defaults: { _controller: SejourBundle:Jour:jourAddEvent }
jour_dellevent:
    path:   /jour/{id}/dell
    defaults: { _controller: SejourBundle:Jour:jourDellEvent }
jour_editevent:
    path:   /evenement/{id}/edit
    defaults: { _controller: SejourBundle:Jour:jourEditEvent }
jour_affecterenfant:
    path:   /jour/{idJour}/affecter/{idEnfant}
    defaults: { _controller: SejourBundle:Jour:jourAffecterEnfant }
jour_modifenfant:
    path:   /jour/{idJour}/modifier/{idEnfant}
    defaults: { _controller: SejourBundle:Jour:jourModifierEnfant }
evenement_toPdf:
    path:   /{idEv}/pdf
    defaults:  { _controller: SejourBundle:Listing:evenementToPdf }
