services:
#    sejour.example:
#        class: SejourBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    sejour.droits:
        class: SejourBundle\Droits\droits
        arguments: [ "@doctrine.orm.entity_manager", "@=service('security.token_storage').getToken().getUser()" ]